/*
 * This source file was generated by the Gradle 'init' task
 */

package com.xoff.chessvger.parser.player;

import java.sql.SQLException;
import java.util.List;


public class RunPlayerParser implements Runnable {
  @Override
  public void run() {

    System.out.println("Start runAppProducerPlayer");

    System.out.println("avant le consumer player");
    String filename = "./data/players_list_xml_foa.xml";

    System.out.println("AppProducerPlayer::Start to parse:" + filename);
    manageFile(filename);

  }

  /**
   * @param filedir ex "data/players_list_xml_foa.xml"
   */
  private void manageFile(String filedir) {

    CommonPlayerDao commonPlayerDao = new CommonPlayerDao();
    System.out.println("managerFile " + filedir);
    PlayerParser playerParser = new PlayerParser();
    List<CommonPlayer> players = playerParser.parse(filedir);
    long id = 1L;
    for (CommonPlayer player : players) {

      player.setId(id++);
      try {
        commonPlayerDao.insertCommonPlayer(player);
      } catch (SQLException e) {
        throw new RuntimeException(e);
      } catch (ClassNotFoundException e) {
        throw new RuntimeException(e);
      }
    }
    System.out.println("players inserted: " + players.size());

  }

}
