# docker compose up -d 
# docker system prune
# docker-compose down --volumes
networks:
  chessvger_network:
    driver: bridge

services:
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - chessvger_network   
    volumes:
      - ./data:/app/metrics 

  chessvger-backoffice:
    image: chessvger-backoffice:latest
    depends_on:
      - zipkin
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - chessvger_network
    volumes:
      - ./data:/app/data  
      
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - chessvger_network

  postgres:
    image: postgres:latest
    container_name: postgres_container
    hostname: db_chessvger
    environment:
      POSTGRES_USER: chessvger
      POSTGRES_PASSWORD: chessvger
      POSTGRES_DB: chessvger
    ports:
      - "5432:5432"
    networks:
      - chessvger_network
    volumes:
      - ./reference/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./data/postgres_data:/var/lib/postgresql/data

  
  # dockfish:
  #   image: registry.gitlab.com/ce72/dockfish:latest 
  #   build:
  #     context: ./dockfish 
  #   ports:
  #     - "8084:8080"
  #   networks:
  #   - chessvger_network


  chessvger-serverapp:
    image: chessvger-serverapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - chessvger_network
    volumes:
      - ./data:/app/data   
    ports:
      - "8080:8080"

  chessvger-serverapp-admin:
    image: chessvger-serverapp-admin:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - chessvger_network
    volumes:
      - ./data:/app/data   
    ports:
      - "8082:8082"

  chessvger-client:
    image: chessvger-client:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - chessvger_network
    ports:
      - "3000:3000"

  chessvger-client-admin:
    image: chessvger-client-admin:latest
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - chessvger_network
    ports:
      - "3002:3002"
           


