# docker compose up
# docker system prune
# docker-compose down --volumes
networks:
  chessvger_network:
    driver: bridge

services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    networks:
      - chessvger_network


  postgres:
    image: postgres:latest
    container_name: postgres_container
    hostname: db_chessvger
    environment:
      POSTGRES_USER: chessvger
      POSTGRES_PASSWORD: chessvger
      POSTGRES_DB: chessvger
    ports:
      - "5432:5432"
    networks:
      - chessvger_network
    volumes:
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - postgres_data:/var/lib/postgresql/data
      
  # dockfish:
  #   image: registry.gitlab.com/ce72/dockfish:latest 
  #   build:
  #     context: ./dockfish 
  #   ports:
  #     - "8084:8080"
  #   networks:
  #   - chessvger_network


  chessvger-monitor:
    image: chessvger-monitor:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    networks:
      - chessvger_network

  chessvger-webapp:
    image: chessvger-webapp:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - chessvger-monitor
    networks:
      - chessvger_network
    volumes:
      - ./data:/app/data   
    ports:
      - "8080:8080"

  chessvger-client:
    image: chessvger-client:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - chessvger-webapp
    networks:
      - chessvger_network
    ports:
      - "3000:3000"
      
  chessvger-parser:
    image: chessvger-parser:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - chessvger-webapp
    networks:
      - chessvger_network
    volumes:
      - ./data:/app/data  

volumes:
  postgres_data:
    driver: local