/*
 * This source file was generated by the Gradle 'init' task
 */

package com.xoff.chessvger.parser.game;

import java.io.File;
import java.sql.SQLException;
import java.util.List;

public class RunGameParser implements Runnable {
  /**
   * @param filedir ex /data/twic114
   */
  private static void manageFile(String filedir) {
    System.out.println("games " + filedir);
    CommonGameDao commonGameDao = new CommonGameDao();

    Parser parser = new Parser();
    List<CommonGame> games = parser.parseDir(new File(filedir));
    System.out.println("games " + games.size());
    long id = 1L;
    for (CommonGame game : games) {

      game.setId(id++);

      try {
        commonGameDao.insertCommonGame(game);
      } catch (SQLException e) {
        throw new RuntimeException(e);
      } catch (ClassNotFoundException e) {
        throw new RuntimeException(e);
      }
      // mettre a jour le reconciliation manager
      // envoyer sur les stats browser
      // envoyer game of player
      // List<CoupleZobristMaterial> list = MaterialPositionsUtil.parseMoves2(game.getMoves());
      // PositionMaterialProducer.enqueuePositionMaterial(game.getId(), list);
      //enqueueGameOfAPlayer(game.getId(), game.getWhiteFideId());
      //enqueueGameOfAPlayer(game.getId(), game.getBlackFideId());
      //ReconciliationManager.update(game.getId(), ReconciliationType.GAME);
    }
    System.out.println("db insert games done " + games.size());
  }

  @Override
  public void run() {


    System.out.println("Start parse");
    String filename = "./data/twic";
    manageFile(filename);
    System.out.println("finish to parse:" + filename);


  }


}
