/*
 * This source file was generated by the Gradle 'init' task
 */

package com.xoff.chessvger.parser.game;

import com.xoff.chessvger.topic.Topic;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import redis.clients.jedis.Jedis;

public class RunGameParser implements Runnable {

  private final String folder;

  public RunGameParser(String folder) {
    this.folder = folder;
  }


  private static void manageFile(String filedir) throws IOException,SQLException {
    System.out.println("games " + filedir);
    CommonGameDao commonGameDao = new CommonGameDao();
    Parser parser = new Parser();
    long start = System.currentTimeMillis();
    List<CommonGame> games = parser.parseDir(new File(filedir));

    long finish1 = System.currentTimeMillis();
    long timeElapsed = (finish1 - start) / 1000;
    System.out.println("after parse games done: " + games.size() + ":" + timeElapsed + " s");


    long id = commonGameDao.count()+1;
    for (CommonGame game : games) {

      game.setId(id++);

      try {
        commonGameDao.insertCommonGame(game);
      } catch (SQLException e) {
        throw new RuntimeException(e);
      } catch (ClassNotFoundException e) {
        throw new RuntimeException(e);
      }
      // mettre a jour le reconciliation manager
      // envoyer sur les stats browser
      // envoyer game of player
      // List<CoupleZobristMaterial> list = MaterialPositionsUtil.parseMoves2(game.getMoves());
      // PositionMaterialProducer.enqueuePositionMaterial(game.getId(), list);
      //enqueueGameOfAPlayer(game.getId(), game.getWhiteFideId());
      //enqueueGameOfAPlayer(game.getId(), game.getBlackFideId());
      //ReconciliationManager.update(game.getId(), ReconciliationType.GAME);
    }
    long finish2 = System.currentTimeMillis();
    timeElapsed = (finish2 - finish1) / 1000;
    System.out.println("db insert games done " + games.size() + ":" + timeElapsed + " s");
    try (Jedis jedis = new Jedis("redis", 6379)) {
      // TODO a externaliser
      jedis.publish(Topic.TOPIC_FROM_QUEUE, games.size() + ":" + timeElapsed + " s");
    }
    System.out.println("Apres l envoi: db insert games done " + games.size() + ":" + timeElapsed + " s");
  }

  @Override
  public void run() {

    try {
      manageFile(folder);
    } catch (IOException e) {
      throw new RuntimeException(e);
    } catch (SQLException e) {
      throw new RuntimeException(e);
    }
  }


}
