/*
 * This source file was generated by the Gradle 'init' task
 */

package com.xoff.chessvger.backoffice.environnement;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.xoff.chessvger.backoffice.game.Parser;
import com.xoff.chessvger.backoffice.materialposition.MaterialPositionsUtil;
import com.xoff.chessvger.chess.board.CoupleZobristMaterial;
import com.xoff.chessvger.dao.*;
import com.xoff.chessvger.model.CommonGame;
import com.xoff.chessvger.topic.MessageFromParser;
import com.xoff.chessvger.topic.MessageToParser;
import com.xoff.chessvger.topic.ResultAction;
import com.xoff.chessvger.topic.Topic;
import lombok.extern.slf4j.Slf4j;
import redis.clients.jedis.Jedis;

import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;

@Slf4j
public class RunGameParser implements Runnable {

    private final MessageToParser messageToParser;

    public RunGameParser(MessageToParser messageToParser) {
        this.messageToParser = messageToParser;
    }


    private static void manageFile(MessageToParser messageToParser) throws IOException, SQLException {
        // TODO quelle bd? celle donnee par le nom du schema
        log.info("games " + messageToParser);
        GameDao commonGameDao = new GameDao();
        Parser parser = new Parser();
        long start = System.currentTimeMillis();
        List<CommonGame> games = parser.parseDir(new File(messageToParser.getFolderToParse()));

        long finish1 = System.currentTimeMillis();
        long timeElapsed = (finish1 - start) / 1000;
        log.info("after parse games : nb games to insert: " + games.size() + ":" + timeElapsed + " s");
        log.info("after parse games done: " + messageToParser);

        try (Connection connection = CommonDao.getConnection(messageToParser.getDatabaseName())) {
            Connection connectionClickHouse=CommonDao.getConnectionClickHouse();
            long id = commonGameDao.count(connection, messageToParser.getSchema()) + 1;
            List <CommonGame>   gamesWork=new ArrayList<>();
           
            for (CommonGame game : games) {

                game.setId(id++);

                commonGameDao.insertCommonGame(connection, messageToParser.getSchema(), game);
                gamesWork.add(game);
                GameOfAPlayerDao.insert(connection, messageToParser.getSchema(), game.getId(), game.getWhitePlayer(), game.getWhiteFideId());
                GameOfAPlayerDao.insert(connection, messageToParser.getSchema(), game.getId(), game.getBlackPlayer(), game.getBlackFideId());
                List<CoupleZobristMaterial> list = MaterialPositionsUtil.parseMoves2(game.getMoves());
                //MaterialDao.insert(connection, messageToParser.getSchema(), game.getId(), list);
                //PositionDao.insert(connection, messageToParser.getSchema(), game.getId(), list);
                PositionClickHouseDao.insert(connectionClickHouse,messageToParser.getSchema(), messageToParser.getTenantId(),messageToParser.getDatabaseId(),game.getId(),  list);;

            }
            /*
            faire le clean des doublons dans position et material @TODO
            UPDATE %s.position_games
            SET game_ids = (
                    SELECT ARRAY(
                    SELECT DISTINCT unnest_id
                    FROM unnest(game_ids) AS unnest_id
                    ORDER BY unnest_id
            )
)
            WHERE value IN (1, 2, 3);
            */
            log.info("db insert games all done " + games.size() + ":" + timeElapsed + " s");
            BrowserDao.createStatsForGames(connection, messageToParser.getSchema(), gamesWork);
            log.info("browseFirstMove done ");

        } catch (SQLException e) {
            log.error("runGame Parser  erreur", e);


        } catch (ClassNotFoundException e) {
            log.error("runGame Parser  erreur", e);

        }
        long finish2 = System.currentTimeMillis();
        timeElapsed = (finish2 - finish1) / 1000;
        log.info("db insert games done " + games.size() + ":" + timeElapsed + " s");
        try (Jedis jedis = new Jedis("redis", 6379)) {
            // TODO a externaliser
            MessageFromParser messageFromParser = new MessageFromParser();
            // TODO
            // private long tenantId;
            messageFromParser.setCorrelationId(messageToParser.getCorrelationId());
            messageFromParser.setTenantId(messageFromParser.getTenantId());
            messageFromParser.setResult(ResultAction.SUCCESS);
            messageFromParser.setMessage(games.size() + ":" + timeElapsed + " s");
            ObjectMapper objectMapper = new ObjectMapper();

            jedis.publish(Topic.TOPIC_FROM_QUEUE, objectMapper.writeValueAsString(messageFromParser));
        } finally {
            log.info(
                    "Apres l envoi: db insert games done " + games.size() + ":" + timeElapsed + " s");
        }
    }

    @Override
    public void run() {

        try {
            manageFile(messageToParser);
        } catch (IOException e) {
            log.error("runGame Parser  erreur", e);
        } catch (SQLException e) {
            log.error("runGame Parser  erreur", e);
        }
    }


}
