/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    copy: typeof import('./components/GameBrowse copy.vue')['default']
    DatabaseDetail: typeof import('./components/DatabaseDetail.vue')['default']
    DatabasesList: typeof import('./components/DatabasesList.vue')['default']
    DEPHelloWorld: typeof import('./components/DEPHelloWorld.vue')['default']
    GameBrowse: typeof import('./components/GameBrowse.vue')['default']
    GamePlayers: typeof import('./components/GamePlayers.vue')['default']
    GamesList: typeof import('./components/GamesList.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WebSocketChat: typeof import('./components/WebSocketChat.vue')['default']
  }
}
