/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    Board: typeof import('./components/Board.vue')['default']
    Chat: typeof import('./components/Chat.vue')['default']
    DatabaseDetail: typeof import('./components/DatabaseDetail.vue')['default']
    DatabasesList: typeof import('./components/DatabasesList.vue')['default']
    Game: typeof import('./components/Game.vue')['default']
    GameBrowse: typeof import('./components/GameBrowse.vue')['default']
    GamePlayers: typeof import('./components/GamePlayers.vue')['default']
    GamesList: typeof import('./components/GamesList.vue')['default']
    HomePage: typeof import('./components/HomePage.vue')['default']
    LandingPage: typeof import('./components/LandingPage.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserInfo: typeof import('./components/UserInfo.vue')['default']
  }
}
