/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

pluginManagement {
    // Include 'plugins build' to define convention plugins.
    //includeBuild("build-logic")
}

rootProject.name = "chessvger"
include("backoffice")
include("core")
include("web")
include("web_admin")
