/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AppHeader: typeof import('./components/AppHeader.vue')['default']
    FeatureFlags: typeof import('./components/FeatureFlags.vue')['default']
    FeatureFlagsForm: typeof import('./components/FeatureFlagsForm.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    ModalSearchPlayer: typeof import('./components/ModalSearchPlayer.vue')['default']
    PlayersList: typeof import('./components/PlayersList.vue')['default']
    PlayersSearchDialog: typeof import('./components/PlayersSearchDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Stats: typeof import('./components/Stats.vue')['default']
    UsersForm: typeof import('./components/UsersForm.vue')['default']
    UsersList: typeof import('./components/UsersList.vue')['default']
    WebSocketChat: typeof import('./components/WebSocketChat.vue')['default']
  }
}
